src/common/command.rs, src/webelement.rs, webappdemo/src/components/inputs.rs
`get_property` has a typo which makes the call returned as `unknown function` from selenium server.
`get_property` also returning the value as its original type, which means for example with boolean property it would cause panic on `serde_json` parse value at `convert_json` in `connection_common`.
I'm proposing a check if the origin type is not string and parse it as string before handling to `convert_json`
```rust
pub fn convert_json<T>(value: &serde_json::Value) -> WebDriverResult<T>
where
T: DeserializeOwned,
{
let s: T = serde_json::from_value(value.clone())?;
Ok(s)
}
```
```rust
if !is_string(&v["value"]) {
return convert_json(&json!(&v["value"].to_string()))
}
```
=> fix get_property method

src/common/capabilities/firefox.rs
Hey @stevepryde great crate.
I was willing to use firefox driver in headless mode and noticed that chrome has this option but firefox doesn't so I decided to provide such a straightforward PR.
comment: The chrome and firefox args functions are literally identical so might it's worth to have some basic trait or whatever in order to reduce a copy/paste :)
=> Add set_headless method to FirefoxCapabilities

src/common/command.rs, src/lib.rs, src/sync/webdrivercommands.rs, src/webdrivercommands.rs
**Description**
This PR will enable users to execute browser specific commands. [It is not breaking W3C standards](https://w3c.github.io/webdriver/#extensions-0) . And already implemented in [geckodriver](https://hg.mozilla.org/mozilla-central/file/tip/testing/geckodriver/src/command.rs#l118) and  [chromedriver](https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/chrome/test/chromedriver/client/command_executor.py#206). 
**My Usecase**
I want to install a browser addon to firefox using the geckodriver.
=> Extensions command feature

Cargo.toml, src/http_async/surf_async.rs
Async-std-runtime feature was not building, `surf::RequestBuilder::body_json` does not exist
Fixes #22
=> FIX: async-std-runtime feature

src/common/capabilities/desiredcapabilities.rs
Setting any options to `None`, causes this type of error
with geckodriver.
```
An argument passed to the WebDriver server was invalid:
Status: 400
Additional info:
noProxy is not an array: null
Error: invalid argument
Stacktrace:
```
Not de-serialize settings if they are equal `None` resolves
the issue.
I am not confident to say if the issue relates only to `geckodriver`.
=> make proxy settings optional

src/common/capabilities/desiredcapabilities.rs
Tested that `socks_proxy.is_some()` && `socks_version.is_none()` causes an error.
Setting `sock_version` to some number eliminate the issue.
closes #27
=> Add socks_version proxy setting

src/webdriver.rs
Currently, the `WebDriver::new` method does not allow the user to set a timeout for the `POST /session` request. This value is hardcoded to 120 seconds in case of the reqwest driver (haven't looked up the others).
Especially in a cloud context where sessions are not available immediately, this can cause issues. I'm currently in the process of evaluating [WebGrid](https://github.com/TilBlechschmidt/WebGrid) in GCE where nodes take about a minute or two to scale up, causing the session creation to take up to three minutes (running into the hardcoded timeout).
I presume that similar issues can be encountered when using Zalenium.
=> Add timeout option for session creation

src/common/connection_common.rs, src/http/surf_async.rs
This PRs adds the equivalent to build_reqwest_headers for surf in order to add support for authentication. Without this change, I am getting this error: UnknownResponse(401, "Authorization required").
Solves #52
=> feat: add common headers for async-std-runtime

src/webdrivercommands.rs
I have not found any specific place where this is described in the protocol, but it seems to me that this field should have this name. 
In the Response from the remote server in a third party service, I am receiving session_id as sessionId and also I think that this is the equivalent to this part in the python client.
https://github.com/SeleniumHQ/selenium/blob/0580ff2cace55c3e52f743356586c64865413677/py/selenium/webdriver/remote/webdriver.py#L309
What do you think? @stevepryde
I am not sure how to create a test or spawn a chromiumdriver server that will have a response with that format.
=> fix: change name of field in ConnectionResp

src/common/capabilities/firefox.rs
Renamed ReforefoxProfile into FirefoxPreferences,
Changed to work like Capabilities,
Added helper methods,
Without doc comments
#56
=> FirefoxProfile into FirefoxPreferences

src/common/cookie.rs
Since I needed to specify the same site attribute in our use case, I added an API that allows user to specify the same site in cookie.
=> Add the same site attribute to cookie

src/extensions/firefox/firefoxcommand.rs, src/extensions/firefox/firefoxtools.rs
Add support for a Firefox extension, enabling to screenshot the whole page, not just the part into the viewport.
This extension has been added to geckodriver following this bug report:
https://bugzilla.mozilla.org/show_bug.cgi?id=1431148
The implementation and the WebDriver endpoint can be found here:
https://hg.mozilla.org/mozilla-central/file/fef96678ad06/testing/geckodriver/src/command.rs#l53
I tried to follow the the naming conventions, but of course feel free to rename the functions or change how errors are handled.
=> Add full-page screenshot Firefox extension

src/common/capabilities/firefox.rs
Firefox uses `pageLoadStrategy` (https://searchfox.org/mozilla-central/source/remote/shared/webdriver/Capabilities.jsm#441).
=> Fix Firefox's pageLoadStrategy setting

src/common/capabilities/chrome.rs, src/common/capabilities/firefox.rs, src/webelement.rs
`FirefoxCapabilities::new` calls `FirefoxCapabilities::default` which only adds `"browserName"` as a key to `FirefoxCapabilities::capabilities`.
`FirefoxCapabilities::get_args` can therefor panic because it does not necessarily contain `"moz:firefoxOptions" `.
This PR fixes this issue.
=> fix FirefoxCapabilities::get_args

Cargo.toml, src/webdriver.rs
This prevents `hyper-tls` from being pulled in accidentally.
=> Set default-features to false for fantoccini

src/extensions/query/element_query.rs
Make `ElementQueryable::query` accessible through `SessionHandle`s. Currently the trait is implemented for `WebDriver` and `WebElement` but not `SessionHandle`, which may be surprising to users.
=> Implement ElementQueryable for SessionHandle

thirtyfour/Cargo.toml
Fixes #103
Selenium version >= 4 requires the parameter `charset=utf-8` included on the `Content-Type` header. Version `0.19.3` of Fantoccini includes this fix.
=> Bump fantoccini version to 0.19.3

thirtyfour/Cargo.toml, thirtyfour/README.md, thirtyfour/src/lib.rs, thirtyfour/src/webdriver.rs
Found it by accident as I entered `rusttls` into [crates.io](https://crates.io/search?page=1&per_page=10&q=rusttls).
NOTE: ignore typo in branch name
=> Fixed typo rusttls into correct rustls (no double t)

thirtyfour/src/js.rs, thirtyfour/src/lib.rs, thirtyfour/src/webelement.rs, thirtyfour/tests/common.rs, thirtyfour/tests/custom_js.rs, thirtyfour/tests/test_html/drag_to.html
Currently the drag and drop methods in action chain do not work due to a known bug in Selenium. The solution for the python library was to have a method which simulates drag and drop using JavaScript be part of an external library called seletools. Since thirtyfour is already a wrapper around fantoccini which provides it's own API's, it made more sense to me that the solution for thirtyfour would be to provide a convenience method that executed the same Javascript functionality, which could be deprecated when the bug is fixed in Selenium. This pull request implements that method.
=> Added temporary js_drag_to method to WebElement

thirtyfour/Cargo.toml
These dependencies seem not to be used.
=> Remove unused dependencies

thirtyfour/src/common/capabilities/desiredcapabilities.rs
it appears that a spec change made a long time ago has renamed the respective capability:
https://github.com/w3c/webdriver/commit/df3b04aebbcc755f2bd429383b2a60cbbaf1b3fd
https://www.w3.org/2016/09/19-webdriver-minutes.html
https://www.w3.org/TR/2022/WD-webdriver2-20221216/#capabilities
the new name works with up to date webdriver implementations while the old one does not.
until this is stable, the following workaround can be used for `v0.31.0`:
```
use thirtyfour::CapabilitiesHelper;                                                             
let mut caps = DesiredCapabilities::chrome();                                                   
caps.add("acceptInsecureCerts", true);                  
```
thank you for your work.
=> Rename accept_ssl_certs -> accept_insecure_certs (in line with webdriver spec)

thirtyfour/src/webelement.rs
When the page has a fixed navbar (like in material-ui), and we want to focus a link before clicking it, scroll_into_view may leave the link behind the navbar, therefore not clickable.
This change makes the javascript call of scrollIntoView try to align the element in the center x/y axes of the viewport, ensuring the element is not obscured by fixed navigational elements in the viewport margins. (https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)
If scroll_into_view still leaves the element obscured by such navigational elements, then it's likely a user wouldn't be able to scroll them into view either, so the user's UI needs to be fixed.
I propose changing the current scroll_into_view instead of creating a new method with the extra params because this seems to be a …
=> Make scroll_into_view account for fixed navbars

thirtyfour/src/extensions/cdp/chromecommand.rs
The `execute_cdp_with_params` function is not working on v0.32.0-rc.9, this patch re-adds the missing body params for the command
=> Add missing body params for the ExecuteCdpCommand

thirtyfour/src/components/wrapper/resolver.rs
only invalidate initialized `OnceCells` (the less `OnceCells` we create the less times we query the browser)
=> update resolver to fight less over cache
